import { LightningInputs, LightningStep, ChatMessage } from '../../types/lightningMode';
import { startBackgroundProcessing, markQuestionsComplete } from './backgroundProcessing';

// Track question processing to prevent duplicate responses
let q1Processed = false;
let q2Processed = false;
let q3Processed = false;

// Track last processed responses to prevent rapid duplicates
let lastQ1Response: string | null = null;
let lastQ2Response: string | null = null;
let lastQ3Response: string | null = null;

// Session timeout
let sessionTimeoutId: NodeJS.Timeout | null = null;
const SESSION_TIMEOUT_MS = 30 * 60 * 1000; // 30 minutes

/**
 * Start session timeout
 */
function startSessionTimeout(): void {
  // Clear existing timeout
  if (sessionTimeoutId) {
    clearTimeout(sessionTimeoutId);
  }
  
  // Set new timeout
  sessionTimeoutId = setTimeout(() => {
    console.log('🔍 Lightning Mode session timed out');
    // End session logic would go here
  }, SESSION_TIMEOUT_MS);
}

/**
 * Handle Q1 Response - Product/Service Focus
 */
export async function handleQ1Response(productFocus: string, inputs: LightningInputs): Promise<ChatMessage> {
  const now = Date.now();
  
  // Check if this exact response was processed recently
  if (lastQ1Response === productFocus && q1Processed) {
    console.log('🔍 Q1 duplicate response detected, skipping...');
    return {
      id: `lightning_q1_duplicate_${now}`,
      role: 'assistant',
      content: '', // Empty content to prevent display
      timestamp: now,
      lightningMode: {
        type: 'lightning_mode',
        step: LightningStep.PERSONALIZATION,
        data: { inputs, answers: { q1: productFocus } },
        timestamp: now
      }
    };
  }
  
  lastQ1Response = productFocus;
  q1Processed = true;
  
  // Reset session timeout
  startSessionTimeout();
  
  console.log('🔍 Q1 Response received:', productFocus);
  
  // Get current lightning data and update with Q1 answer
  let lightningData: any = { inputs, answers: {}, step: 'q1', timestamp: Date.now() };
  if (typeof window !== 'undefined') {
    const stored = localStorage.getItem('lightningModeData');
    if (stored) {
      try {
        lightningData = JSON.parse(stored);
      } catch (error) {
        console.error('Error parsing stored lightning data:', error);
      }
    }
  }
  
  // Update with Q1 answer
  lightningData.answers.q1 = productFocus;
  lightningData.step = 'q2';
  lightningData.timestamp = Date.now();
  
  if (typeof window !== 'undefined') {
    localStorage.setItem('lightningModeData', JSON.stringify(lightningData));
  }
  
  // Company summary generation is now handled by startBackgroundProcessing
  // No need to generate it again here to avoid duplication
  console.log('🔍 Q1 completed, company summary will be generated by startBackgroundProcessing...');
  
  return {
    id: `lightning_q2_${Date.now()}`,
    role: 'assistant',
    content: formatOutreachPreferenceQuestion(),
    timestamp: Date.now(),
    lightningMode: {
      type: 'lightning_mode',
      step: LightningStep.PERSONALIZATION,
      data: lightningData,
      timestamp: Date.now()
    }
  };
}

/**
 * Handle Q2 Response - Outreach Preference
 */
export async function handleQ2Response(outreachPreference: string, lightningData: any): Promise<ChatMessage> {
  const now = Date.now();
  
  // Check if this exact response was processed recently
  if (lastQ2Response === outreachPreference && q2Processed) {
    console.log('🔍 Q2 duplicate response detected, skipping...');
    return {
      id: `lightning_q2_duplicate_${now}`,
      role: 'assistant',
      content: '', // Empty content to prevent display
      timestamp: now,
      lightningMode: {
        type: 'lightning_mode',
        step: LightningStep.PERSONALIZATION,
        data: lightningData,
        timestamp: now
      }
    };
  }
  
  lastQ2Response = outreachPreference;
  q2Processed = true;
  
  // Reset session timeout
  startSessionTimeout();
  
  console.log('🔍 Q2 Response received:', outreachPreference);
  
  // Update with Q2 answer
  const updatedData = {
    ...lightningData,
    answers: {
      ...lightningData.answers,
      q2: outreachPreference
    },
    step: 'q3',
    timestamp: Date.now()
  };
  
  if (typeof window !== 'undefined') {
    localStorage.setItem('lightningModeData', JSON.stringify(updatedData));
  }
  
  return {
    id: `lightning_q3_${Date.now()}`,
    role: 'assistant',
    content: formatLeadHandoffPreferenceQuestion(),
    timestamp: Date.now(),
    lightningMode: {
      type: 'lightning_mode',
      step: LightningStep.PERSONALIZATION,
      data: updatedData,
      timestamp: Date.now()
    }
  };
}

/**
 * Handle Q3 Response - Lead Handoff Preference (Final Question)
 */
export async function handleQ3Response(leadHandoffPreference: string, lightningData: any): Promise<ChatMessage> {
  const now = Date.now();
  
  // Check if this exact response was processed recently
  if (lastQ3Response === leadHandoffPreference && q3Processed) {
    console.log('🔍 Q3 duplicate response detected, skipping...');
    return {
      id: `lightning_q3_duplicate_${now}`,
      role: 'assistant',
      content: '', // Empty content to prevent display
      timestamp: now,
      lightningMode: {
        type: 'lightning_mode',
        step: LightningStep.RESEARCH,
        data: lightningData,
        timestamp: now
      }
    };
  }
  
  lastQ3Response = leadHandoffPreference;
  q3Processed = true;
  
  // Reset session timeout
  startSessionTimeout();
  
  console.log('🔍 Q3 Response received:', leadHandoffPreference);
  
  // Update with Q3 answer
  const updatedData = {
    ...lightningData,
    answers: {
      ...lightningData.answers,
      q3: leadHandoffPreference
    },
    step: 'results_display',
    timestamp: Date.now()
  };
  
  if (typeof window !== 'undefined') {
    localStorage.setItem('lightningModeData', JSON.stringify(updatedData));
  }
  
  // Mark all questions as complete
  markQuestionsComplete();
  
  // Q&A completed - now post the company summary
  console.log('🔍 Q&A completed. Posting company summary...');
  
  // Post company summary with enhanced retry mechanism
  if (typeof window !== 'undefined') {
    // Enhanced retry logic: 40 attempts, 1 second each (40 seconds total)
    let attempts = 0;
    const maxAttempts = 40; // Increased from 10 to 40
    const retryInterval = 1000; // 1 second
    
    const postSummaryWithRetry = async () => {
      const companySummary = localStorage.getItem('lightning_company_summary');
      const summaryReady = localStorage.getItem('lightning_summary_ready');
      
      console.log(`🔍 Retry attempt ${attempts + 1}: checking for summary...`, {
        hasSummary: !!companySummary,
        summaryReady: summaryReady,
        summaryLength: companySummary?.length || 0
      });
      
      if (companySummary && summaryReady === 'true') {
        // Check if already posted
        const alreadyPosted = localStorage.getItem('lightning_summary_posted');
        if (alreadyPosted === 'true') {
          console.log('🔍 Company summary already posted, skipping...');
          return;
        }
        
        // Post the summary
        console.log('🔍 Posting company summary to chat...');
        window.dispatchEvent(new CustomEvent('postLightningMessage', {
          detail: {
            content: companySummary,
            type: 'company_summary',
            timestamp: Date.now()
          }
        }));
        
        // Mark as posted
        localStorage.setItem('lightning_summary_posted', 'true');
        console.log('✅ Company summary posted successfully');
        return;
      }
      
      // If summary not ready, check if we should retry
      if (attempts < maxAttempts) {
        attempts++;
        console.log(`🔍 Company summary not ready yet, retrying (${attempts}/${maxAttempts})...`);
        
        // If we're at attempt 5, 10, 15, etc., try to trigger background processing again
        if (attempts % 5 === 0) {
          console.log('🔍 Attempting to re-trigger background processing...');
          const lightningData = localStorage.getItem('lightningModeData');
          if (lightningData) {
            try {
              const data = JSON.parse(lightningData);
              if (data.inputs) {
                console.log('🔍 Re-triggering background processing with stored inputs...');
                const { startBackgroundProcessing } = await import('./backgroundProcessing');
                startBackgroundProcessing(data.inputs);
              }
            } catch (error) {
              console.error('Error re-triggering background processing:', error);
            }
          }
        }
        
        setTimeout(postSummaryWithRetry, retryInterval);
      } else {
        console.warn('⚠️ Company summary not ready after maximum retries (40 seconds)');
        
        // Check if there's a rate limit error stored
        const storedSummary = localStorage.getItem('lightning_company_summary');
        const isRateLimitError = storedSummary && (
          storedSummary.includes('Service Temporarily Unavailable') || 
          storedSummary.includes('high demand') ||
          storedSummary.includes('lightning-error-message')
        );
        
        if (isRateLimitError) {
          // Post the rate limit error message
          window.dispatchEvent(new CustomEvent('postLightningMessage', {
            detail: {
              content: storedSummary,
              type: 'error',
              isHTML: true,
              timestamp: Date.now()
            }
          }));
          localStorage.setItem('lightning_summary_posted', 'true');
          console.log('⚠️ Rate limit error message posted');
        } else {
          // As a fallback, show a user-friendly error message
          console.log('🔍 Showing service unavailable message...');
          const lightningData = localStorage.getItem('lightningModeData');
          if (lightningData) {
            try {
              const data = JSON.parse(lightningData);
              if (data.inputs) {
                const errorMessage = `<div class="lightning-error-message" style="padding: 24px; background: linear-gradient(135deg, rgba(59, 130, 246, 0.15) 0%, rgba(37, 99, 235, 0.1) 100%); backdrop-filter: blur(12px); -webkit-backdrop-filter: blur(12px); border-radius: 16px; border: 1px solid rgba(59, 130, 246, 0.3); box-shadow: 0 8px 32px rgba(59, 130, 246, 0.15); margin: 16px 0;">
                  <h3 style="color: #60A5FA; margin: 0 0 12px 0; font-size: 18px; font-weight: 600;">⚠️ Service Temporarily Unavailable</h3>
                  <p style="color: #93C5FD; margin: 0 0 16px 0; line-height: 1.6;">We're experiencing high demand at the moment. Our AI services are temporarily at capacity.</p>
                  <div style="background: rgba(255,255,255,0.08); padding: 14px; border-radius: 10px; border: 1px solid rgba(59, 130, 246, 0.2);">
                    <p style="color: #60A5FA; margin: 0; font-weight: 500;">🔄 What to do:</p>
                    <ul style="color: #93C5FD; margin: 8px 0 0 0; padding-left: 20px;">
                      <li>Please wait a few minutes</li>
                      <li>Start a new Lightning Mode session</li>
                      <li>Try again with your company information</li>
                    </ul>
                  </div>
                </div>`;
                
                // Post error message
                window.dispatchEvent(new CustomEvent('postLightningMessage', {
                  detail: {
                    content: errorMessage,
                    type: 'error',
                    isHTML: true,
                    timestamp: Date.now()
                  }
                }));
                
                localStorage.setItem('lightning_summary_posted', 'true');
                console.log('⚠️ Service unavailable message posted');
              }
            } catch (error) {
              console.error('Error generating error message:', error);
            }
          }
        }
      }
    };
    
    // Start posting with retry after a short delay
    setTimeout(postSummaryWithRetry, 1000); // Start after 1 second
  }
  
  return {
    id: `lightning_qa_complete_${Date.now()}`,
    role: 'assistant',
    content: `**✅ Information Gathering Complete!**\n\nThank you for completing all three questions! Your personalized analysis is being prepared.\n\n**What happens next:**\n1. 📊 **Company Analysis** - Detailed analysis of your business (appears below in 10-20 seconds)\n2. 🎯 **Target Audience** - Review and edit your target criteria\n3. 📋 **Prospects List** - Generate real companies matching your criteria\n\n*Your company analysis and target audience will appear below shortly...*`,
    timestamp: Date.now(),
    lightningMode: {
      type: 'lightning_mode',
      step: LightningStep.RESEARCH,
      data: updatedData,
      timestamp: Date.now()
    }
  };
}

/**
 * Format Q2 - Outreach Preference question with proper HTML formatting
 */
function formatOutreachPreferenceQuestion(): string {
  let content = `<div style="margin: 20px 0; padding: 16px;">`;
  
  content += `<div style="margin-bottom: 20px;">`;
  content += `<h3 style="color: #E2E8F0; margin-bottom: 12px; font-size: 18px; font-weight: 500;">Q2. Outreach Preference</h3>`;
  content += `<p style="color: #CBD5E1; margin-bottom: 16px; font-size: 14px; line-height: 1.5;">How do you prefer to reach out to prospects?</p>`;
  content += `</div>`;
  
  content += `<div style="display: flex; flex-wrap: wrap; gap: 12px; margin: 20px 0;">`;
  content += `<button onclick="handleQ2Response('Email')" style="background: rgba(255, 255, 255, 0.1); backdrop-filter: blur(15px); border: 1px solid rgba(59, 130, 246, 0.3); color: white; padding: 14px 24px; border-radius: 12px; cursor: pointer; font-weight: 600; font-size: 14px; transition: all 0.3s ease; box-shadow: 0 4px 16px rgba(0, 0, 0, 0.2), inset 0 1px 0 rgba(255, 255, 255, 0.1); min-width: 120px;" onmouseover="this.style.background='rgba(59, 130, 246, 0.1)'; this.style.borderColor='rgba(59, 130, 246, 0.5)'; this.style.boxShadow='0 8px 24px rgba(59, 130, 246, 0.2), inset 0 1px 0 rgba(255, 255, 255, 0.2)'; this.style.transform='translateY(-2px)'" onmouseout="this.style.background='rgba(255, 255, 255, 0.1)'; this.style.borderColor='rgba(59, 130, 246, 0.3)'; this.style.boxShadow='0 4px 16px rgba(0, 0, 0, 0.2), inset 0 1px 0 rgba(255, 255, 255, 0.1)'; this.style.transform='translateY(0)'">`;
  content += `Email`;
  content += `</button>`;
  content += `<button onclick="handleQ2Response('Phone (Cold Call / SMS / WhatsApp)')" style="background: rgba(255, 255, 255, 0.1); backdrop-filter: blur(15px); border: 1px solid rgba(139, 92, 246, 0.3); color: white; padding: 14px 24px; border-radius: 12px; cursor: pointer; font-weight: 600; font-size: 14px; transition: all 0.3s ease; box-shadow: 0 4px 16px rgba(0, 0, 0, 0.2), inset 0 1px 0 rgba(255, 255, 255, 0.1); min-width: 200px;" onmouseover="this.style.background='rgba(139, 92, 246, 0.1)'; this.style.borderColor='rgba(139, 92, 246, 0.5)'; this.style.boxShadow='0 8px 24px rgba(139, 92, 246, 0.2), inset 0 1px 0 rgba(255, 255, 255, 0.2)'; this.style.transform='translateY(-2px)'" onmouseout="this.style.background='rgba(255, 255, 255, 0.1)'; this.style.borderColor='rgba(139, 92, 246, 0.3)'; this.style.boxShadow='0 4px 16px rgba(0, 0, 0, 0.2), inset 0 1px 0 rgba(255, 255, 255, 0.1)'; this.style.transform='translateY(0)'">`;
  content += `Phone (Cold Call / SMS / WhatsApp)`;
  content += `</button>`;
  content += `<button onclick="handleQ2Response('Social Media (LinkedIn, FB, X, Insta)')" style="background: rgba(255, 255, 255, 0.1); backdrop-filter: blur(15px); border: 1px solid rgba(59, 130, 246, 0.3); color: white; padding: 14px 24px; border-radius: 12px; cursor: pointer; font-weight: 600; font-size: 14px; transition: all 0.3s ease; box-shadow: 0 4px 16px rgba(0, 0, 0, 0.2), inset 0 1px 0 rgba(255, 255, 255, 0.1); min-width: 200px;" onmouseover="this.style.background='rgba(59, 130, 246, 0.1)'; this.style.borderColor='rgba(59, 130, 246, 0.5)'; this.style.boxShadow='0 8px 24px rgba(59, 130, 246, 0.2), inset 0 1px 0 rgba(255, 255, 255, 0.2)'; this.style.transform='translateY(-2px)'" onmouseout="this.style.background='rgba(255, 255, 255, 0.1)'; this.style.borderColor='rgba(59, 130, 246, 0.3)'; this.style.boxShadow='0 4px 16px rgba(0, 0, 0, 0.2), inset 0 1px 0 rgba(255, 255, 255, 0.1)'; this.style.transform='translateY(0)'">`;
  content += `Social Media (LinkedIn, FB, X, Insta)`;
  content += `</button>`;
  content += `<button onclick="handleQ2Response('Other')" style="background: rgba(255, 255, 255, 0.1); backdrop-filter: blur(15px); border: 1px solid rgba(139, 92, 246, 0.3); color: white; padding: 14px 24px; border-radius: 12px; cursor: pointer; font-weight: 600; font-size: 14px; transition: all 0.3s ease; box-shadow: 0 4px 16px rgba(0, 0, 0, 0.2), inset 0 1px 0 rgba(255, 255, 255, 0.1); min-width: 120px;" onmouseover="this.style.background='rgba(139, 92, 246, 0.1)'; this.style.borderColor='rgba(139, 92, 246, 0.5)'; this.style.boxShadow='0 8px 24px rgba(139, 92, 246, 0.2), inset 0 1px 0 rgba(255, 255, 255, 0.2)'; this.style.transform='translateY(-2px)'" onmouseout="this.style.background='rgba(255, 255, 255, 0.1)'; this.style.borderColor='rgba(139, 92, 246, 0.3)'; this.style.boxShadow='0 4px 16px rgba(0, 0, 0, 0.2), inset 0 1px 0 rgba(255, 255, 255, 0.1)'; this.style.transform='translateY(0)'">`;
  content += `Other`;
  content += `</button>`;
  content += `</div>`;
  
  content += `<p style="color: #94A3B8; font-size: 14px; text-align: center; margin-top: 16px;"></p>`;
  
  content += `</div>`;
  
  return content;
}

/**
 * Format Q3 - Lead Handoff Preference question with proper HTML formatting
 */
function formatLeadHandoffPreferenceQuestion(): string {
  let content = `<div style="margin: 20px 0; padding: 16px;">`;
  
  content += `<div style="margin-bottom: 20px;">`;
  content += `<h3 style="color: #E2E8F0; margin-bottom: 12px; font-size: 18px; font-weight: 500;">Q3. Lead Handoff Preference</h3>`;
  content += `<p style="color: #CBD5E1; margin-bottom: 16px; font-size: 14px; line-height: 1.5;">How would you like to receive qualified leads?</p>`;
  content += `</div>`;
  
  content += `<div style="display: flex; flex-wrap: wrap; gap: 12px; margin: 20px 0;">`;
  content += `<button onclick="handleQ3Response('SalesCentri LMS')" style="background: rgba(255, 255, 255, 0.1); backdrop-filter: blur(15px); border: 1px solid rgba(59, 130, 246, 0.3); color: white; padding: 14px 24px; border-radius: 12px; cursor: pointer; font-weight: 600; font-size: 14px; transition: all 0.3s ease; box-shadow: 0 4px 16px rgba(0, 0, 0, 0.2), inset 0 1px 0 rgba(255, 255, 255, 0.1); min-width: 140px;" onmouseover="this.style.background='rgba(59, 130, 246, 0.1)'; this.style.borderColor='rgba(59, 130, 246, 0.5)'; this.style.boxShadow='0 8px 24px rgba(59, 130, 246, 0.2), inset 0 1px 0 rgba(255, 255, 255, 0.2)'; this.style.transform='translateY(-2px)'" onmouseout="this.style.background='rgba(255, 255, 255, 0.1)'; this.style.borderColor='rgba(59, 130, 246, 0.3)'; this.style.boxShadow='0 4px 16px rgba(0, 0, 0, 0.2), inset 0 1px 0 rgba(255, 255, 255, 0.1)'; this.style.transform='translateY(0)'">`;
  content += `SalesCentri LMS`;
  content += `</button>`;
  content += `<button onclick="handleQ3Response('Own LMS/CRM')" style="background: rgba(255, 255, 255, 0.1); backdrop-filter: blur(15px); border: 1px solid rgba(139, 92, 246, 0.3); color: white; padding: 14px 24px; border-radius: 12px; cursor: pointer; font-weight: 600; font-size: 14px; transition: all 0.3s ease; box-shadow: 0 4px 16px rgba(0, 0, 0, 0.2), inset 0 1px 0 rgba(255, 255, 255, 0.1); min-width: 140px;" onmouseover="this.style.background='rgba(139, 92, 246, 0.1)'; this.style.borderColor='rgba(139, 92, 246, 0.5)'; this.style.boxShadow='0 8px 24px rgba(139, 92, 246, 0.2), inset 0 1px 0 rgba(255, 255, 255, 0.2)'; this.style.transform='translateY(-2px)'" onmouseout="this.style.background='rgba(255, 255, 255, 0.1)'; this.style.borderColor='rgba(139, 92, 246, 0.3)'; this.style.boxShadow='0 4px 16px rgba(0, 0, 0, 0.2), inset 0 1px 0 rgba(255, 255, 255, 0.1)'; this.style.transform='translateY(0)'">`;
  content += `Own LMS/CRM`;
  content += `</button>`;
  content += `<button onclick="handleQ3Response('Email')" style="background: rgba(255, 255, 255, 0.1); backdrop-filter: blur(15px); border: 1px solid rgba(59, 130, 246, 0.3); color: white; padding: 14px 24px; border-radius: 12px; cursor: pointer; font-weight: 600; font-size: 14px; transition: all 0.3s ease; box-shadow: 0 4px 16px rgba(0, 0, 0, 0.2), inset 0 1px 0 rgba(255, 255, 255, 0.1); min-width: 120px;" onmouseover="this.style.background='rgba(59, 130, 246, 0.1)'; this.style.borderColor='rgba(59, 130, 246, 0.5)'; this.style.boxShadow='0 8px 24px rgba(59, 130, 246, 0.2), inset 0 1px 0 rgba(255, 255, 255, 0.2)'; this.style.transform='translateY(-2px)'" onmouseout="this.style.background='rgba(255, 255, 255, 0.1)'; this.style.borderColor='rgba(59, 130, 246, 0.3)'; this.style.boxShadow='0 4px 16px rgba(0, 0, 0, 0.2), inset 0 1px 0 rgba(255, 255, 255, 0.1)'; this.style.transform='translateY(0)'">`;
  content += `Email`;
  content += `</button>`;
  content += `<button onclick="handleQ3Response('Website Form')" style="background: rgba(255, 255, 255, 0.1); backdrop-filter: blur(15px); border: 1px solid rgba(139, 92, 246, 0.3); color: white; padding: 14px 24px; border-radius: 12px; cursor: pointer; font-weight: 600; font-size: 14px; transition: all 0.3s ease; box-shadow: 0 4px 16px rgba(0, 0, 0, 0.2), inset 0 1px 0 rgba(255, 255, 255, 0.1); min-width: 140px;" onmouseover="this.style.background='rgba(139, 92, 246, 0.1)'; this.style.borderColor='rgba(139, 92, 246, 0.5)'; this.style.boxShadow='0 8px 24px rgba(139, 92, 246, 0.2), inset 0 1px 0 rgba(255, 255, 255, 0.2)'; this.style.transform='translateY(-2px)'" onmouseout="this.style.background='rgba(255, 255, 255, 0.1)'; this.style.borderColor='rgba(139, 92, 246, 0.3)'; this.style.boxShadow='0 4px 16px rgba(0, 0, 0, 0.2), inset 0 1px 0 rgba(255, 255, 255, 0.1)'; this.style.transform='translateY(0)'">`;
  content += `Website Form`;
  content += `</button>`;
  content += `<button onclick="handleQ3Response('Phone / WhatsApp')" style="background: rgba(255, 255, 255, 0.1); backdrop-filter: blur(15px); border: 1px solid rgba(59, 130, 246, 0.3); color: white; padding: 14px 24px; border-radius: 12px; cursor: pointer; font-weight: 600; font-size: 14px; transition: all 0.3s ease; box-shadow: 0 4px 16px rgba(0, 0, 0, 0.2), inset 0 1px 0 rgba(255, 255, 255, 0.1); min-width: 160px;" onmouseover="this.style.background='rgba(59, 130, 246, 0.1)'; this.style.borderColor='rgba(59, 130, 246, 0.5)'; this.style.boxShadow='0 8px 24px rgba(59, 130, 246, 0.2), inset 0 1px 0 rgba(255, 255, 255, 0.2)'; this.style.transform='translateY(-2px)'" onmouseout="this.style.background='rgba(255, 255, 255, 0.1)'; this.style.borderColor='rgba(59, 130, 246, 0.3)'; this.style.boxShadow='0 4px 16px rgba(0, 0, 0, 0.2), inset 0 1px 0 rgba(255, 255, 255, 0.1)'; this.style.transform='translateY(0)'">`;
  content += `Phone / WhatsApp`;
  content += `</button>`;
  content += `<button onclick="handleQ3Response('Other')" style="background: rgba(255, 255, 255, 0.1); backdrop-filter: blur(15px); border: 1px solid rgba(139, 92, 246, 0.3); color: white; padding: 14px 24px; border-radius: 12px; cursor: pointer; font-weight: 600; font-size: 14px; transition: all 0.3s ease; box-shadow: 0 4px 16px rgba(0, 0, 0, 0.2), inset 0 1px 0 rgba(255, 255, 255, 0.1); min-width: 120px;" onmouseover="this.style.background='rgba(139, 92, 246, 0.1)'; this.style.borderColor='rgba(139, 92, 246, 0.5)'; this.style.boxShadow='0 8px 24px rgba(139, 92, 246, 0.2), inset 0 1px 0 rgba(255, 255, 255, 0.2)'; this.style.transform='translateY(-2px)'" onmouseout="this.style.background='rgba(255, 255, 255, 0.1)'; this.style.borderColor='rgba(139, 92, 246, 0.3)'; this.style.boxShadow='0 4px 16px rgba(0, 0, 0, 0.2), inset 0 1px 0 rgba(255, 255, 255, 0.1)'; this.style.transform='translateY(0)'">`;
  content += `Other`;
  content += `</button>`;
  content += `</div>`;
  
  content += `<p style="color: #94A3B8; font-size: 14px; text-align: center; margin-top: 16px;"></p>`;
  
  content += `</div>`;
  
  return content;
}

// Export functions
export { formatOutreachPreferenceQuestion, formatLeadHandoffPreferenceQuestion };
