openapi: 3.0.3
info:
  title: AI Call API
  description: Endpoints for managing AI call records
  version: 1.0.0
servers:
  - url: /api
    description: API Server

paths:
  /ai-call.php/register:
    post:
      $ref: "./register.yaml#/post"

  /ai-call.php/{id}:
    patch:
      $ref: "./update.yaml#/patch"
    get:
      $ref: "./get-by-id.yaml#/get"

  /ai-call.php:
    get:
      $ref: "./list.yaml#/get"

components:
  $ref: "./schemas.yaml#/components"
